# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sean's Personal Site
description: A place for Sean's thoughts
repository: https://github.com/skolk
# baseurl: /
url: https://skolk.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Skolk
email: sean.kolk@mgail.com

collections:
  portfolio:
    output: true
    sortby: date
  press:
    sortby: date

defaults:
  - scope:
      path: "portfolio"
    values:
      layout: "portfolio"

navigation:
  - text: Home
    url: /

  - text: Docs
    url: /docs

  - text: Examples
    url: /examples

  - text: Log
    url: /log

  - text: Portfolio
    url: /portfolio.html

social:
  - service: github
    username: skolk
    link: https://github.com/skolk
  - service: twitter
    username: S_kolk
    link: https://twitter.com/s_kolk

# Plugins
gems:
  - jekyll-seo-tag
